//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not convert {0} to {1}.
        /// </summary>
        internal static string CanNotConvertException {
            get {
                return ResourceManager.GetString("CanNotConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Aborted.
        /// </summary>
        internal static string ExecutionAborted {
            get {
                return ResourceManager.GetString("ExecutionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to new the object.
        /// </summary>
        internal static string FailedNewException {
            get {
                return ResourceManager.GetString("FailedNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invliad format before =, only variable can be placed here.
        /// </summary>
        internal static string InvalidBeforeEqual {
            get {
                return ResourceManager.GetString("InvalidBeforeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid value format: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not boolean value.
        /// </summary>
        internal static string NotBoolean {
            get {
                return ResourceManager.GetString("NotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not number.
        /// </summary>
        internal static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value assined.
        /// </summary>
        internal static string NoValueAssigned {
            get {
                return ResourceManager.GetString("NoValueAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value can not be null.
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only variable can accepted.
        /// </summary>
        internal static string OnlyVariableAccept {
            get {
                return ResourceManager.GetString("OnlyVariableAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter can not be null.
        /// </summary>
        internal static string ParameterNullException {
            get {
                return ResourceManager.GetString("ParameterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string value only support +=.
        /// </summary>
        internal static string StringOnlySupport {
            get {
                return ResourceManager.GetString("StringOnlySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test condition can not be null.
        /// </summary>
        internal static string TestNullException {
            get {
                return ResourceManager.GetString("TestNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception.
        /// </summary>
        internal static string UnknowException {
            get {
                return ResourceManager.GetString("UnknowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable already defined.
        /// </summary>
        internal static string VariableDefinedExcepiton {
            get {
                return ResourceManager.GetString("VariableDefinedExcepiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name can not be null.
        /// </summary>
        internal static string VariableNameException {
            get {
                return ResourceManager.GetString("VariableNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable {0} was not defined.
        /// </summary>
        internal static string VariableNotDefined {
            get {
                return ResourceManager.GetString("VariableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the variable value can not be null.
        /// </summary>
        internal static string VariableNullException {
            get {
                return ResourceManager.GetString("VariableNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong string format.
        /// </summary>
        internal static string WrongStringFormat {
            get {
                return ResourceManager.GetString("WrongStringFormat", resourceCulture);
            }
        }
    }
}
