//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index is out of the range.
        /// </summary>
        internal static string IndexOutOfRangeException {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not an array.
        /// </summary>
        internal static string NotArrayException {
            get {
                return ResourceManager.GetString("NotArrayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not an array, list or dictionary.
        /// </summary>
        internal static string NotCollectionException {
            get {
                return ResourceManager.GetString("NotCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not an array.
        /// </summary>
        internal static string NotNumberException {
            get {
                return ResourceManager.GetString("NotNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Exception.
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value can not be null.
        /// </summary>
        internal static string ValueNullException {
            get {
                return ResourceManager.GetString("ValueNullException", resourceCulture);
            }
        }
    }
}
