//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absolute value of a number.
        /// </summary>
        internal static string AbsDescription {
            get {
                return ResourceManager.GetString("AbsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the angle whose cosine is the specified number.
        /// </summary>
        internal static string AcosDescription {
            get {
                return ResourceManager.GetString("AcosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the angle whose cotangent is the specified number.
        /// </summary>
        internal static string ACtgDescription {
            get {
                return ResourceManager.GetString("ACtgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the angle whose sine is the specified number.
        /// </summary>
        internal static string ASinDescription {
            get {
                return ResourceManager.GetString("ASinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the angle whose tangent is the specified number.
        /// </summary>
        internal static string AtanDescription {
            get {
                return ResourceManager.GetString("AtanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the cosine of the specified angle.
        /// </summary>
        internal static string CosDescription {
            get {
                return ResourceManager.GetString("CosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the cotangent of the specified angle.
        /// </summary>
        internal static string CtgDescription {
            get {
                return ResourceManager.GetString("CtgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to math function.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural logarithmic base, specified by the constant e.
        /// </summary>
        internal static string EDescription {
            get {
                return ResourceManager.GetString("EDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to math.
        /// </summary>
        internal static string MathCategory {
            get {
                return ResourceManager.GetString("MathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get max number from two number.
        /// </summary>
        internal static string MaxDescription {
            get {
                return ResourceManager.GetString("MaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get min number from two number.
        /// </summary>
        internal static string MinDescription {
            get {
                return ResourceManager.GetString("MinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not a number.
        /// </summary>
        internal static string NotNumberException {
            get {
                return ResourceManager.GetString("NotNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Exception.
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constant π.
        /// </summary>
        internal static string PiDescription {
            get {
                return ResourceManager.GetString("PiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random number.
        /// </summary>
        internal static string RandomDescription {
            get {
                return ResourceManager.GetString("RandomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the sine of the specified angle.
        /// </summary>
        internal static string SinDescription {
            get {
                return ResourceManager.GetString("SinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the tangent of the specified angle.
        /// </summary>
        internal static string TanDescription {
            get {
                return ResourceManager.GetString("TanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trigonometry.
        /// </summary>
        internal static string TriangleCategory {
            get {
                return ResourceManager.GetString("TriangleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown exception.
        /// </summary>
        internal static string UnknowException {
            get {
                return ResourceManager.GetString("UnknowException", resourceCulture);
            }
        }
    }
}
