//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a boolean parameter.
        /// </summary>
        public static string AddBoolParameter {
            get {
                return ResourceManager.GetString("AddBoolParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a number parameter.
        /// </summary>
        public static string AddNumberParameter {
            get {
                return ResourceManager.GetString("AddNumberParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a string parameter.
        /// </summary>
        public static string AddStringParameter {
            get {
                return ResourceManager.GetString("AddStringParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Function.
        /// </summary>
        public static string CreateFuncTitle {
            get {
                return ResourceManager.GetString("CreateFuncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function name is already defined, please use another name!.
        /// </summary>
        public static string FuncNameExisted {
            get {
                return ResourceManager.GetString("FuncNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function name.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function name.
        /// </summary>
        public static string InvalidFuncName {
            get {
                return ResourceManager.GetString("InvalidFuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter name.
        /// </summary>
        public static string InvalidParameterName {
            get {
                return ResourceManager.GetString("InvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variable name.
        /// </summary>
        public static string InvalidVariableName {
            get {
                return ResourceManager.GetString("InvalidVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Remove library.
        /// </summary>
        public static string LibraryDesc {
            get {
                return ResourceManager.GetString("LibraryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name {0} is invalid.
        /// </summary>
        public static string ParameterNameInvalid {
            get {
                return ResourceManager.GetString("ParameterNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter name can not be same.
        /// </summary>
        public static string ParameterNameSame {
            get {
                return ResourceManager.GetString("ParameterNameSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Variable Name.
        /// </summary>
        public static string SetVarTitle {
            get {
                return ResourceManager.GetString("SetVarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Name:.
        /// </summary>
        public static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name {0} is invalid.
        /// </summary>
        public static string VariableNameInvalid {
            get {
                return ResourceManager.GetString("VariableNameInvalid", resourceCulture);
            }
        }
    }
}
