//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string a_Hide {
            get {
                return ResourceManager.GetString("a_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string m_Move {
            get {
                return ResourceManager.GetString("m_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string m_Step {
            get {
                return ResourceManager.GetString("m_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn into a wall に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string m_Wall {
            get {
                return ResourceManager.GetString("m_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_CharacterImg {
            get {
                return ResourceManager.GetString("xaml_CharacterImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modeling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_Modeling {
            get {
                return ResourceManager.GetString("xaml_Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_NewRole {
            get {
                return ResourceManager.GetString("xaml_NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_Roles {
            get {
                return ResourceManager.GetString("xaml_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_Sound {
            get {
                return ResourceManager.GetString("xaml_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Control {
            get {
                return ResourceManager.GetString("xc_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Data {
            get {
                return ResourceManager.GetString("xc_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Event {
            get {
                return ResourceManager.GetString("xc_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exterior に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Exterior {
            get {
                return ResourceManager.GetString("xc_Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Logic {
            get {
                return ResourceManager.GetString("xc_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Method {
            get {
                return ResourceManager.GetString("xc_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Motion {
            get {
                return ResourceManager.GetString("xc_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xc_Operation {
            get {
                return ResourceManager.GetString("xc_Operation", resourceCulture);
            }
        }
    }
}
