//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchEditor.localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchEditor.localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnBool {
            get {
                return ResourceManager.GetString("btnBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create the Building Blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnCreateBlocks {
            get {
                return ResourceManager.GetString("btnCreateBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnCreateVariables {
            get {
                return ResourceManager.GetString("btnCreateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnNumber {
            get {
                return ResourceManager.GetString("btnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnString {
            get {
                return ResourceManager.GetString("btnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnText {
            get {
                return ResourceManager.GetString("btnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a boolean parameter： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAddBoolParam {
            get {
                return ResourceManager.GetString("lblAddBoolParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a numeric parameter： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAddNumericParam {
            get {
                return ResourceManager.GetString("lblAddNumericParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a string parameter： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAddStringParam {
            get {
                return ResourceManager.GetString("lblAddStringParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a text label： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAddTextLabel {
            get {
                return ResourceManager.GetString("lblAddTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Variable Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string title_SetVariable {
            get {
                return ResourceManager.GetString("title_SetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply for all roles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_Global {
            get {
                return ResourceManager.GetString("xaml_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply for all roles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_Local {
            get {
                return ResourceManager.GetString("xaml_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable Name： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xaml_VariableName {
            get {
                return ResourceManager.GetString("xaml_VariableName", resourceCulture);
            }
        }
    }
}
