//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string a_Hide {
            get {
                return ResourceManager.GetString("a_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary.
        /// </summary>
        public static string cs_Arbitrary {
            get {
                return ResourceManager.GetString("cs_Arbitrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string cs_Background {
            get {
                return ResourceManager.GetString("cs_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the picture to.
        /// </summary>
        public static string cs_ChangePicture {
            get {
                return ResourceManager.GetString("cs_ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set x to.
        /// </summary>
        public static string cs_Coordinates_X {
            get {
                return ResourceManager.GetString("cs_Coordinates_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string cs_Degree {
            get {
                return ResourceManager.GetString("cs_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string cs_In {
            get {
                return ResourceManager.GetString("cs_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose to.
        /// </summary>
        public static string cs_LoseTo {
            get {
                return ResourceManager.GetString("cs_LoseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip left and right.
        /// </summary>
        public static string cs_LRFlip {
            get {
                return ResourceManager.GetString("cs_LRFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to coordinate X in seconds .
        /// </summary>
        public static string cs_MoveXinSec {
            get {
                return ResourceManager.GetString("cs_MoveXinSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not flipped.
        /// </summary>
        public static string cs_NoFlip {
            get {
                return ResourceManager.GetString("cs_NoFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        public static string cs_Say {
            get {
                return ResourceManager.GetString("cs_Say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Direction To.
        /// </summary>
        public static string cs_SetDirection {
            get {
                return ResourceManager.GetString("cs_SetDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the rotation mode.
        /// </summary>
        public static string cs_SetRotationMode {
            get {
                return ResourceManager.GetString("cs_SetRotationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set size to.
        /// </summary>
        public static string cs_SetSizeTo {
            get {
                return ResourceManager.GetString("cs_SetSizeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string cs_Show {
            get {
                return ResourceManager.GetString("cs_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next picture.
        /// </summary>
        public static string cs_ShowNextImg {
            get {
                return ResourceManager.GetString("cs_ShowNextImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string cs_Spin {
            get {
                return ResourceManager.GetString("cs_Spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking.
        /// </summary>
        public static string cs_Thinking {
            get {
                return ResourceManager.GetString("cs_Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the Left.
        /// </summary>
        public static string cs_ToLeft {
            get {
                return ResourceManager.GetString("cs_ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log window.
        /// </summary>
        public static string cs_ToLogWindow {
            get {
                return ResourceManager.GetString("cs_ToLogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the Right.
        /// </summary>
        public static string cs_ToRight {
            get {
                return ResourceManager.GetString("cs_ToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Coordinate is set to .
        /// </summary>
        public static string cs_X_CoordinatesSetTo {
            get {
                return ResourceManager.GetString("cs_X_CoordinatesSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Coordinate is set to .
        /// </summary>
        public static string cs_Y_CoordinatesSetTo {
            get {
                return ResourceManager.GetString("cs_Y_CoordinatesSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string m_Move {
            get {
                return ResourceManager.GetString("m_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string m_Step {
            get {
                return ResourceManager.GetString("m_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If on edge, bounce.
        /// </summary>
        public static string m_Wall {
            get {
                return ResourceManager.GetString("m_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Image.
        /// </summary>
        public static string xaml_CharacterImg {
            get {
                return ResourceManager.GetString("xaml_CharacterImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling.
        /// </summary>
        public static string xaml_Modeling {
            get {
                return ResourceManager.GetString("xaml_Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string xaml_NewRole {
            get {
                return ResourceManager.GetString("xaml_NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string xaml_Roles {
            get {
                return ResourceManager.GetString("xaml_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string xaml_Sound {
            get {
                return ResourceManager.GetString("xaml_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string xc_Control {
            get {
                return ResourceManager.GetString("xc_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string xc_Event {
            get {
                return ResourceManager.GetString("xc_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic.
        /// </summary>
        public static string xc_Logic {
            get {
                return ResourceManager.GetString("xc_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks.
        /// </summary>
        public static string xc_Looks {
            get {
                return ResourceManager.GetString("xc_Looks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Blocks.
        /// </summary>
        public static string xc_Method {
            get {
                return ResourceManager.GetString("xc_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        public static string xc_Motion {
            get {
                return ResourceManager.GetString("xc_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string xc_Operation {
            get {
                return ResourceManager.GetString("xc_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string xc_Variable {
            get {
                return ResourceManager.GetString("xc_Variable", resourceCulture);
            }
        }
    }
}
