//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AbountTitle {
            get {
                return ResourceManager.GetString("AbountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application aborted!.
        /// </summary>
        public static string ApplicationAbort {
            get {
                return ResourceManager.GetString("ApplicationAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application complete, Please press any key to close this window.
        /// </summary>
        public static string ApplicationComplete {
            get {
                return ResourceManager.GetString("ApplicationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        public static string ArrayCollection {
            get {
                return ResourceManager.GetString("ArrayCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length of array.
        /// </summary>
        public static string ArrayLengthDescription {
            get {
                return ResourceManager.GetString("ArrayLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array value.
        /// </summary>
        public static string ArrayValueDescription {
            get {
                return ResourceManager.GetString("ArrayValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binary operator.
        /// </summary>
        public static string BinaryExpressionDescription {
            get {
                return ResourceManager.GetString("BinaryExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break in loop and switch.
        /// </summary>
        public static string BreakDescription {
            get {
                return ResourceManager.GetString("BreakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear all text in the console window.
        /// </summary>
        public static string ClearDescription {
            get {
                return ResourceManager.GetString("ClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Error.
        /// </summary>
        public static string ClearError {
            get {
                return ResourceManager.GetString("ClearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string CommentCategory {
            get {
                return ResourceManager.GetString("CommentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentCollection {
            get {
                return ResourceManager.GetString("CommentCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write a comment.
        /// </summary>
        public static string CommentDescription {
            get {
                return ResourceManager.GetString("CommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single line comment.
        /// </summary>
        public static string CommentDescription1 {
            get {
                return ResourceManager.GetString("CommentDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple line comment.
        /// </summary>
        public static string CommentDescription2 {
            get {
                return ResourceManager.GetString("CommentDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beijing Huarui Robotics Ltd,. Co.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional expression.
        /// </summary>
        public static string ConditionExpressionCategory {
            get {
                return ResourceManager.GetString("ConditionExpressionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional expression.
        /// </summary>
        public static string ConditionExpressionDescription {
            get {
                return ResourceManager.GetString("ConditionExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to console.
        /// </summary>
        public static string ConsoleCategory {
            get {
                return ResourceManager.GetString("ConsoleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue in loop.
        /// </summary>
        public static string ContinueDescription {
            get {
                return ResourceManager.GetString("ContinueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright by Beijing Huarui Robotics.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do-while statement.
        /// </summary>
        public static string DoWhileDescription {
            get {
                return ResourceManager.GetString("DoWhileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.
        /// </summary>
        public static string ExampleArray {
            get {
                return ResourceManager.GetString("ExampleArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Dimensional Array.
        /// </summary>
        public static string ExampleArray2 {
            get {
                return ResourceManager.GetString("ExampleArray2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use two dimensional array.
        /// </summary>
        public static string ExampleArray2Desc {
            get {
                return ResourceManager.GetString("ExampleArray2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use array.
        /// </summary>
        public static string ExampleArrayDesc {
            get {
                return ResourceManager.GetString("ExampleArrayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Tree.
        /// </summary>
        public static string ExampleBinaryTree {
            get {
                return ResourceManager.GetString("ExampleBinaryTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use binary tree.
        /// </summary>
        public static string ExampleBinaryTreeDesc {
            get {
                return ResourceManager.GetString("ExampleBinaryTreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint on Canvas.
        /// </summary>
        public static string ExampleCanvas {
            get {
                return ResourceManager.GetString("ExampleCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to paint using Canvas.
        /// </summary>
        public static string ExampleCanvasDesc {
            get {
                return ResourceManager.GetString("ExampleCanvasDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked List.
        /// </summary>
        public static string ExampleLinkedList {
            get {
                return ResourceManager.GetString("ExampleLinkedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use linked list.
        /// </summary>
        public static string ExampleLinkedListDesc {
            get {
                return ResourceManager.GetString("ExampleLinkedListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ExampleList {
            get {
                return ResourceManager.GetString("ExampleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use list.
        /// </summary>
        public static string ExampleListDesc {
            get {
                return ResourceManager.GetString("ExampleListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical.
        /// </summary>
        public static string ExampleLogic {
            get {
                return ResourceManager.GetString("ExampleLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use if statement.
        /// </summary>
        public static string ExampleLogicDesc {
            get {
                return ResourceManager.GetString("ExampleLogicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string ExampleLoop {
            get {
                return ResourceManager.GetString("ExampleLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use loop statement.
        /// </summary>
        public static string ExampleLoopDesc {
            get {
                return ResourceManager.GetString("ExampleLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narcissistic Number.
        /// </summary>
        public static string ExampleNumber {
            get {
                return ResourceManager.GetString("ExampleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example to calculate narcissistic number.
        /// </summary>
        public static string ExampleNumberDesc {
            get {
                return ResourceManager.GetString("ExampleNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Number Calculation.
        /// </summary>
        public static string ExamplePrime {
            get {
                return ResourceManager.GetString("ExamplePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example to show prime number calculation.
        /// </summary>
        public static string ExamplePrimeDesc {
            get {
                return ResourceManager.GetString("ExamplePrimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string ExampleQueue {
            get {
                return ResourceManager.GetString("ExampleQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use queue.
        /// </summary>
        public static string ExampleQueueDesc {
            get {
                return ResourceManager.GetString("ExampleQueueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive Function.
        /// </summary>
        public static string ExampleRecursive {
            get {
                return ResourceManager.GetString("ExampleRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use function and recursive function.
        /// </summary>
        public static string ExampleRecursiveDesc {
            get {
                return ResourceManager.GetString("ExampleRecursiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech synthesis.
        /// </summary>
        public static string ExampleSpeech {
            get {
                return ResourceManager.GetString("ExampleSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use generate the voice.
        /// </summary>
        public static string ExampleSpeechDesc {
            get {
                return ResourceManager.GetString("ExampleSpeechDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string ExampleStack {
            get {
                return ResourceManager.GetString("ExampleStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use stack.
        /// </summary>
        public static string ExampleStackDesc {
            get {
                return ResourceManager.GetString("ExampleStackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example List.
        /// </summary>
        public static string ExampleTitle {
            get {
                return ResourceManager.GetString("ExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Scope.
        /// </summary>
        public static string ExampleVariableScope {
            get {
                return ResourceManager.GetString("ExampleVariableScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use global and local variables.
        /// </summary>
        public static string ExampleVariableScopeDesc {
            get {
                return ResourceManager.GetString("ExampleVariableScopeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during run.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception.
        /// </summary>
        public static string ExceptionCategory {
            get {
                return ResourceManager.GetString("ExceptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excpetion found during run：.
        /// </summary>
        public static string ExceptionDuringRun {
            get {
                return ResourceManager.GetString("ExceptionDuringRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception found when load from {0}.
        /// </summary>
        public static string ExceptionLoadFile {
            get {
                return ResourceManager.GetString("ExceptionLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression statement.
        /// </summary>
        public static string ExpressionStatementCategory {
            get {
                return ResourceManager.GetString("ExpressionStatementCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression as one line.
        /// </summary>
        public static string ExpressionStatementDescription {
            get {
                return ResourceManager.GetString("ExpressionStatementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for statement.
        /// </summary>
        public static string ForDescription {
            get {
                return ResourceManager.GetString("ForDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function call.
        /// </summary>
        public static string FunctionCallCategory {
            get {
                return ResourceManager.GetString("FunctionCallCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string FunctionCollection {
            get {
                return ResourceManager.GetString("FunctionCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create function.
        /// </summary>
        public static string FunctionNewCategory {
            get {
                return ResourceManager.GetString("FunctionNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highligh Running Step and Value.
        /// </summary>
        public static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use this editor.
        /// </summary>
        public static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if.
        /// </summary>
        public static string IfCategory {
            get {
                return ResourceManager.GetString("IfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if statement.
        /// </summary>
        public static string IfDescription {
            get {
                return ResourceManager.GetString("IfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if-else statement.
        /// </summary>
        public static string IfElseStatementDescription {
            get {
                return ResourceManager.GetString("IfElseStatementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if statement.
        /// </summary>
        public static string IfStatementDescription {
            get {
                return ResourceManager.GetString("IfStatementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &amp; Output.
        /// </summary>
        public static string IOCollection {
            get {
                return ResourceManager.GetString("IOCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is changed, please reboot software to take affect..
        /// </summary>
        public static string LanguageChange {
            get {
                return ResourceManager.GetString("LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Library.
        /// </summary>
        public static string LibraryTitle {
            get {
                return ResourceManager.GetString("LibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the exception position?.
        /// </summary>
        public static string LocateException {
            get {
                return ResourceManager.GetString("LocateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logic operation.
        /// </summary>
        public static string LogicCategory {
            get {
                return ResourceManager.GetString("LogicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logic.
        /// </summary>
        public static string LogicValueCategory {
            get {
                return ResourceManager.GetString("LogicValueCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loop.
        /// </summary>
        public static string LoopCategory {
            get {
                return ResourceManager.GetString("LoopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main function is not defined, please add a main function!.
        /// </summary>
        public static string MainNotFound {
            get {
                return ResourceManager.GetString("MainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create an two dimensional array.
        /// </summary>
        public static string NewArray2Description {
            get {
                return ResourceManager.GetString("NewArray2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create an array object.
        /// </summary>
        public static string NewArrayDescription {
            get {
                return ResourceManager.GetString("NewArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a string.
        /// </summary>
        public static string NewStringDescription {
            get {
                return ResourceManager.GetString("NewStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no main function.
        /// </summary>
        public static string NoMain {
            get {
                return ResourceManager.GetString("NoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not expression.
        /// </summary>
        public static string NotExpressionDescription {
            get {
                return ResourceManager.GetString("NotExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        public static string NullCategory {
            get {
                return ResourceManager.GetString("NullCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number &amp; operator.
        /// </summary>
        public static string NumberOperatorCategory {
            get {
                return ResourceManager.GetString("NumberOperatorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a File.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string OperatorCollection {
            get {
                return ResourceManager.GetString("OperatorCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert value to double value.
        /// </summary>
        public static string ParseDoubleDescription {
            get {
                return ResourceManager.GetString("ParseDoubleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert value to float value.
        /// </summary>
        public static string ParseFloatDescription {
            get {
                return ResourceManager.GetString("ParseFloatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert value to integer.
        /// </summary>
        public static string ParseIntDescription {
            get {
                return ResourceManager.GetString("ParseIntDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert value to long value.
        /// </summary>
        public static string ParseLongDescription {
            get {
                return ResourceManager.GetString("ParseLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write text to console.
        /// </summary>
        public static string PrintDescription {
            get {
                return ResourceManager.GetString("PrintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write text to console and followed by the current line terminator.
        /// </summary>
        public static string PrintLnDescription {
            get {
                return ResourceManager.GetString("PrintLnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read one char from console.
        /// </summary>
        public static string ReadDescripiton {
            get {
                return ResourceManager.GetString("ReadDescripiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read text of one line from console.
        /// </summary>
        public static string ReadLnDescription {
            get {
                return ResourceManager.GetString("ReadLnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to rate and review this application in Microsoft store?.
        /// </summary>
        public static string RequestRate {
            get {
                return ResourceManager.GetString("RequestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review.
        /// </summary>
        public static string RequestRateTitle {
            get {
                return ResourceManager.GetString("RequestRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script is modified, would you like to save the script?.
        /// </summary>
        public static string RequestSave {
            get {
                return ResourceManager.GetString("RequestSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save script?.
        /// </summary>
        public static string RequestSaveTitle {
            get {
                return ResourceManager.GetString("RequestSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first time using this tool, Would you like see the video to show how to use this tool?.
        /// </summary>
        public static string RequestVideo {
            get {
                return ResourceManager.GetString("RequestVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        public static string ReturnCategory {
            get {
                return ResourceManager.GetString("ReturnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statement.
        /// </summary>
        public static string ReturnDescription {
            get {
                return ResourceManager.GetString("ReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statement with value.
        /// </summary>
        public static string ReturnValueDescription {
            get {
                return ResourceManager.GetString("ReturnValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excecution Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack exceed the maximum allowed size!.
        /// </summary>
        public static string StackMessage {
            get {
                return ResourceManager.GetString("StackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Overflow.
        /// </summary>
        public static string StackTitle {
            get {
                return ResourceManager.GetString("StackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        public static string StatementCollection {
            get {
                return ResourceManager.GetString("StatementCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string StringCategory {
            get {
                return ResourceManager.GetString("StringCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find index of substring.
        /// </summary>
        public static string StringIndexDescription {
            get {
                return ResourceManager.GetString("StringIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find the last index of substring.
        /// </summary>
        public static string StringLastIndexDescription {
            get {
                return ResourceManager.GetString("StringLastIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string length.
        /// </summary>
        public static string StringLengthDescription {
            get {
                return ResourceManager.GetString("StringLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get substring from position.
        /// </summary>
        public static string StringSubDescription {
            get {
                return ResourceManager.GetString("StringSubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully load script from {0}.
        /// </summary>
        public static string SuccessLodFile {
            get {
                return ResourceManager.GetString("SuccessLodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try-catch statement.
        /// </summary>
        public static string TryDescription {
            get {
                return ResourceManager.GetString("TryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type convertion.
        /// </summary>
        public static string TypeConvertCategory {
            get {
                return ResourceManager.GetString("TypeConvertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update operator.
        /// </summary>
        public static string UpdateExpressionDescription {
            get {
                return ResourceManager.GetString("UpdateExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable assignment.
        /// </summary>
        public static string VariableAssignmentCategory {
            get {
                return ResourceManager.GetString("VariableAssignmentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assign value to variable.
        /// </summary>
        public static string VariableAssignmentDescription {
            get {
                return ResourceManager.GetString("VariableAssignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare a varaible.
        /// </summary>
        public static string VariableDecDescription {
            get {
                return ResourceManager.GetString("VariableDecDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declear a variable and assign value.
        /// </summary>
        public static string VariableDecDescription2 {
            get {
                return ResourceManager.GetString("VariableDecDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable defination.
        /// </summary>
        public static string VariableDefCategory {
            get {
                return ResourceManager.GetString("VariableDefCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string VariableExample {
            get {
                return ResourceManager.GetString("VariableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to define variables.
        /// </summary>
        public static string VariableExampleDescription {
            get {
                return ResourceManager.GetString("VariableExampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &amp; Type.
        /// </summary>
        public static string VariableTypeCollection {
            get {
                return ResourceManager.GetString("VariableTypeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Code Editor.
        /// </summary>
        public static string VisualCodeEditor {
            get {
                return ResourceManager.GetString("VisualCodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.huaruirobot.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while statement.
        /// </summary>
        public static string WhileDescription {
            get {
                return ResourceManager.GetString("WhileDescription", resourceCulture);
            }
        }
    }
}
