//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heading direction.
        /// </summary>
        public static string AngleDescription {
            get {
                return ResourceManager.GetString("AngleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw a arc.
        /// </summary>
        public static string ArcDescription {
            get {
                return ResourceManager.GetString("ArcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear all the drawing.
        /// </summary>
        public static string ClearDescription {
            get {
                return ResourceManager.GetString("ClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        public static string ColorBlackDesc {
            get {
                return ResourceManager.GetString("ColorBlackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string ColorBlueDesc {
            get {
                return ResourceManager.GetString("ColorBlueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        public static string ColorCategory {
            get {
                return ResourceManager.GetString("ColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color values.
        /// </summary>
        public static string ColorCategoryDesc {
            get {
                return ResourceManager.GetString("ColorCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string ColorGreenDesc {
            get {
                return ResourceManager.GetString("ColorGreenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orange.
        /// </summary>
        public static string ColorOrangeDesc {
            get {
                return ResourceManager.GetString("ColorOrangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string ColorRedDesc {
            get {
                return ResourceManager.GetString("ColorRedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is out of range 0 to 255.
        /// </summary>
        public static string ColorValueOutRangeException {
            get {
                return ResourceManager.GetString("ColorValueOutRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string ColorWhiteDesc {
            get {
                return ResourceManager.GetString("ColorWhiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yello.
        /// </summary>
        public static string ColorYellowDesc {
            get {
                return ResourceManager.GetString("ColorYellowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drawing canvas.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw.
        /// </summary>
        public static string DrawCategory {
            get {
                return ResourceManager.GetString("DrawCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw on canvas.
        /// </summary>
        public static string DrawCategoryDesc {
            get {
                return ResourceManager.GetString("DrawCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill color.
        /// </summary>
        public static string FillColorDesc {
            get {
                return ResourceManager.GetString("FillColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        public static string FontSizeDesc {
            get {
                return ResourceManager.GetString("FontSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line color.
        /// </summary>
        public static string LineColorDesc {
            get {
                return ResourceManager.GetString("LineColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw a line.
        /// </summary>
        public static string LineDescription {
            get {
                return ResourceManager.GetString("LineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line thickness.
        /// </summary>
        public static string LineSizeDesc {
            get {
                return ResourceManager.GetString("LineSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw a line to point.
        /// </summary>
        public static string LineToDescription {
            get {
                return ResourceManager.GetString("LineToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to position.
        /// </summary>
        public static string MoveDescription {
            get {
                return ResourceManager.GetString("MoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only color value is accepted.
        /// </summary>
        public static string NotColorException {
            get {
                return ResourceManager.GetString("NotColorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Exception.
        /// </summary>
        public static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        public static string ParameterCategory {
            get {
                return ResourceManager.GetString("ParameterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drawing parameter.
        /// </summary>
        public static string ParameterCategoryDesc {
            get {
                return ResourceManager.GetString("ParameterCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pen down to start painting.
        /// </summary>
        public static string PenDownDescription {
            get {
                return ResourceManager.GetString("PenDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pen up to stop painting.
        /// </summary>
        public static string PenUpDescription {
            get {
                return ResourceManager.GetString("PenUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        public static string PositionCategory {
            get {
                return ResourceManager.GetString("PositionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drawing position.
        /// </summary>
        public static string PositionCategoryDesc {
            get {
                return ResourceManager.GetString("PositionCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset canvas.
        /// </summary>
        public static string ResetDescription {
            get {
                return ResourceManager.GetString("ResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get color from rgb value.
        /// </summary>
        public static string RGBDesc {
            get {
                return ResourceManager.GetString("RGBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate.
        /// </summary>
        public static string RotateDescription {
            get {
                return ResourceManager.GetString("RotateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set font.
        /// </summary>
        public static string SetFontDesc {
            get {
                return ResourceManager.GetString("SetFontDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start fill.
        /// </summary>
        public static string StartFillDescription {
            get {
                return ResourceManager.GetString("StartFillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop fill.
        /// </summary>
        public static string StopFillDescription {
            get {
                return ResourceManager.GetString("StopFillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw a text.
        /// </summary>
        public static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not number.
        /// </summary>
        public static string ValueNotNumberException {
            get {
                return ResourceManager.GetString("ValueNotNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Canvas.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x position.
        /// </summary>
        public static string XPosDescription {
            get {
                return ResourceManager.GetString("XPosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y position.
        /// </summary>
        public static string YPosDescription {
            get {
                return ResourceManager.GetString("YPosDescription", resourceCulture);
            }
        }
    }
}
